### ISSUE TITLE
vsfighting theme

### ISSUE THREAD

**Issue by skysix2** [Snapouille/es-theme-Animatics-DX#1]
HI!

probably not the right place to make requests, I apologize in advance
is it possible to add the "vsfighting" theme? I believe it is an "auto-collection"...

thank's for your job!

**Comment by Snapouille** [comment]
Hi
ok i will do that for the next update

**Comment by Snapouille** [comment]
@skysix2 it's done. You can update to v1.49

![2023-09-03 12_09_05-EmulationStation](https://github.com/Snapouille/es-theme-Animatics-DX/assets/105559045/72b83aed-08c2-4b0d-9825-84117a83a37b)

**Comment by skysix2** [comment]
HI!

Thank you! I have already updated , I checked better and actually it was a dynamic collection and not an automatic one , I think it 's ok anyway , I have to do some tests
