### ISSUE TITLE
Batocera Latest for PC

### ISSUE THREAD

**Issue by mrfomt** [Snapouille/es-theme-Animatics-DX#10]
Installed your theme, animations looks great, but there are no animations on NES system. Watched on youtube and the dog should appear, but on my pc it is only the background with grass and tree.

In game view, are there any way to play the video snap immediately without showing a mix image first?

**Comment by Snapouille** [comment]
Hi, thanks for your feedback
There is indeed a small problem that I need to correct, I'll do that later today.

**Comment by mrfomt** [comment]
Thanks, sounds great!

**Comment by Snapouille** [comment]
I've done the fix, you can update 
(the update number hasn't changed for this little fix, it's still 1.74).
