### ISSUE TITLE
12 hours format clock not showing the AM/PM

### ISSUE THREAD

**Issue by duy64** [Snapouille/es-theme-Animatics-DX#11]
12 hours format not showing AM/PM in retrobat 6.3
![Screenshot 2024-07-28 123041](https://github.com/user-attachments/assets/4034d605-1a53-4ab7-976c-65fe51cca46b)

**Comment by Snapouille** [comment]
Thanks for your feedback, I will fix it for the next UPDATE.

**Comment by Snapouille** [comment]
it's fix in my last update v1.76

![2024-08-06 21_00_06-EmulationStation](https://github.com/user-attachments/assets/6c4bbccf-32b5-46f9-b37a-57b3540afe6b)

![2024-08-06 21_02_31-EmulationStation](https://github.com/user-attachments/assets/2dbd652a-fef9-4271-84d3-238507f72248)
