### ISSUE TITLE
Grey grid system view (New)

### ISSUE THREAD

**Issue by benjdidj** [Snapouille/es-theme-Animatics-DX#13]
First, Thanks for this theme, it is great à lot of infos are shown, and beautiful art.

I guess because this grid system view is new you may be working on it, so if any of what i say is on the go, then thx and sorry for the bother.

1- I'd like to change the color of the boxes in grid(new) system mode other than grey,
 maybe some kind of transparency.
The best would be that they look like the ones in other system modes. (vertical, horizontal)

2- In video mode for the background the video is behind the boxes in grid system, could it be moved to the right to be seen a little more,

Thx for your time, Benjdidj

**Comment by Snapouille** [comment]
Hi, there,
Thanks for your feedback. Yes, the grid system view is still in VIP.

1 - I don't think I'll make a list of choices for the grid color, but I can tell you where to change the color. Could you tell me exactly what color you want?

2 - I haven't worked with the background video yet, but I will soon. The problem is that if I shift the video, there'll be a gap behind the grid, so I'll see what I can do.

**Comment by benjdidj** [comment]
Hi Thank u for answering.
Vous êtes français je crois.
RIen a voir mais j'ai vécu a tahiti de mes 9 ans a 20 ans. en 2000 je passais mon bac lycée La Mennaie.
J'ai vu votre mail avec Tahiti dedans ça m'a fait sourire. Vous êtes toujours la bas ?

Sinon sur le sujet de la discution j'aimerais transparent voire transparent flouté, en fait j'aimerais avoir les mêmes boutons qu'en mode vertical ou horizontal.
Merci pour votre réponse. et votre temps.

Nana.
________________________________
De : Snapouille ***@***.***>
Envoyé : lundi 19 août 2024 09:57
À : Snapouille/es-theme-Animatics-DX ***@***.***>
Cc : benjdidj ***@***.***>; Author ***@***.***>
Objet : Re: [Snapouille/es-theme-Animatics-DX] Grey grid system view (New) (Issue #13)


Hi, there,
Thanks for your feedback. Yes, the grid system view is still in VIP.

1 - I don't think I'll make a list of choices for the grid color, but I can tell you where to change the color. Could you tell me exactly what color you want?

2 - I haven't worked with the background video yet, but I will soon. The problem is that if I shift the video, there'll be a gap behind the grid, so I'll see what I can do.

**Comment by Snapouille** [comment]
Ia Orana,
Oui je suis français, j'ai aussi vécu à Tahiti 4 ans de 2005 à 2007 une première fois et de 2010 à 2012. Je suis rentré en métropole depuis mais une partie de moi même est resté là-bas.

Je regarderai ce que je peux faire comme couleur, mais il faut prendre en compte qu'il faut également une couleur de sélection en plus de la couleur générale de la grille par rapport au mode vertical et horizontal.

Pour l'instant je suis un peu en pose vacances, je reprendrai du service très prochainement ;)
Au plaisir,
Nana

**Comment by benjdidj** [comment]
Je comprend j'ai eu du mal a me faire a la vie en métropole.

Pour la couleur de sélection, c'est déjà ok c'est la couleur du thème. Mon
thème est jaune comme la couleur de sélection.
Juste le gris ne correspond à aucune couleur de thème. C'est juste que je
trouve les cases grises pas jolies contrairement a tout le reste.
En fait les couleurs me sont égales c'est plus:
En mode vertical ou horizontal ou carrousel les boutons sont translucides
et avec un cadre. Je souhaiterais juste qu'ils soit 'identiques'.

bref.
Merci., j'ai choisis le thème parmi tous les autres, je le trouve très
complet.

Reposez vous. Prenez le temps. Si un jour vous bossez un peu dessus. Je
serais ravi de voir les changements.

J'aurais bien essayé mais je ne sais pas comment créer/modifier un thème.
Je ne sais pas coder. Juste un bodouillleur.Je regarderais sur Google.

Mauruuru

**Comment by Snapouille** [comment]
Ia Orana,
J'ai fait quelque test de transparence sur la vue grille mais je ne arriver à rien de satisfaisant, le problème c'est que vu qu'il s'agit de tout un bloc même le système selectionner est aussi en transparence et suivant le background ça peut être soit lisible soit pratiquement pas lisible, ce qui pose problème ...

![2024-08-24 14_15_52-EmulationStation](https://github.com/user-attachments/assets/443b80da-b6a2-4f2f-b80a-93c290f89275)

![2024-08-24 14_15_08-EmulationStation](https://github.com/user-attachments/assets/100e7197-deef-4332-a1ed-b44af6986b9e)

Je vais bosser un peu sur la vidéo ;)
(pour info tu utilises quelle vue système ?)

**Comment by Snapouille** [comment]
J'ai modifier la vue vidéo pour qu'elle passe en full screen, j'ai mis le thème à jour si tu veux tester et me remonter ton avis.
Le prochaine gros chantier sera pour une nouvelle vue gamelist sans parler de toutes les animations que je dois encore faire ...

**Comment by benjdidj** [comment]
Je crois que a première vue sur les Screenshots, j'aime bien.
![image_2024-08-24_163636422](https://github.com/user-attachments/assets/5492558d-556a-49ff-b6ca-c352328b196a)
![Capture d'écran 2024-08-24 163117](https://github.com/user-attachments/assets/362c8e56-cdec-44f7-9256-6a152a2bdad6)
![Capture d'écran 2024-08-24 163353](https://github.com/user-attachments/assets/544b8e75-30cd-4ede-b20c-169f625ee00c)

**Comment by benjdidj** [comment]
9a doit être un boulot massif.

**Comment by Snapouille** [comment]
wouah tu utilises la gamelist et la grille à son maximum, tu dois avoir un sacré écran ou de très bon yeux encore pour te permettre ça '^^
le avatar animation c'est mon petit bébé, c'est lui que je chouchoute le plus, c'est lui aussi qui me demande le plus de boulot, mais bon quand on aime on ne compte pas ...

**Comment by benjdidj** [comment]
bonjour,
pour l'écran, 27 pouce et je suis a 1m. 

En ce moment retrobat crash énormément. Souvent quant je quitte un émulateur ou des fois dans les menus.
Je ne sais pas pourquoi. J'ai beaucoup de roms... 
hate de voir les avancées.. mais prend le temps. :)

**Comment by Snapouille** [comment]
Salut,
Les mises à niveau avancent bien, j'ai eu pas mal de réorganisation de codage à faire qui prend un temps assez conséquent. Tu verras il y aura pas mal de changement au programme, il y a aussi une nouvelle vue qui est faite pour matcher avec la vue système grille.

![2024-08-28 09_27_55-Window](https://github.com/user-attachments/assets/0f31f498-a32d-432d-930e-9a7208b26591)

![2024-08-28 09_27_55-Window](https://github.com/user-attachments/assets/fb8516db-ac65-42a5-93d1-cfcdb58db820)

**Comment by Snapouille** [comment]
Pour Retrobat j'aime bien l'utiliser pour coder mon thème car c'est vraiment pratique de le faire sur PC et de directement avoir le rendu à coter. Sinon j'utilise beaucoup plus Batocera que je trouve personnellement plus stable et fiable.
Je sais pas si c'est du au fait que tu as bcp de roms, moi j'ai arrêter les fulls sets il y a un moment, je ne me consacre plus qu'au petit set, avec des jeux choisis à la loupe dont j'ai vraiment envie de jouer. Quand j'avais que des full sets je me rendais compte que je jouais jamais à rien.

**Comment by Snapouille** [comment]
La mise à jour est en ligne. 
N'hésites pas à me faire remonter tes impressions et suggestions.
Bon amusement
Nana

**Comment by benjdidj** [comment]
C'est fantastique.
 J'ai complètement effacé le thème animatics manuellement et le config associé et réinstallé animatics.
Tout marche à merveille plus de crash (j'en avait vraiment beaucoup, un pb de fichier mal téléchargé ou config je sais pas...)

J'aime beaucoup les quelques nouveautés que j'ai vu....
Merci pour ton boulot.

Je m'éclate comme un fou à essayer de faire marcher tout ça et tous ces émulateurs obscurs.
________________________________
De : Snapouille ***@***.***>
Envoyé : samedi 7 septembre 2024 09:27
À : Snapouille/es-theme-Animatics-DX ***@***.***>
Cc : benjdidj ***@***.***>; Author ***@***.***>
Objet : Re: [Snapouille/es-theme-Animatics-DX] Grey grid system view (New) (Issue #13)


La mise à jour est en ligne.
N'hésites pas à me faire remonter tes impressions et suggestions.
Bon amusement
Nana

**Comment by benjdidj** [comment]
> Ia Orana, J'ai fait quelque test de transparence sur la vue grille mais je ne suis arriver à rien de satisfaisant, le problème c'est que vu qu'il s'agit de tout un bloc même le système selectionner est aussi en transparence et suivant le background ça peut être soit lisible soit pratiquement pas lisible, ce qui pose problème ...
> 
> ![2024-08-24 14_15_52-EmulationStation](https://private-user-images.githubusercontent.com/105559045/361139901-443b80da-b6a2-4f2f-b80a-93c290f89275.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTcwMjcsIm5iZiI6MTcyNTg5NjcyNywicGF0aCI6Ii8xMDU1NTkwNDUvMzYxMTM5OTAxLTQ0M2I4MGRhLWI2YTItNGYyZi1iODBhLTkzYzI5MGY4OTI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNTQ1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGEyMTY4MTk1MTQ3Y2I3M2Q4MDAyZGUyMTE1M2Q4NGQxNmViZTQ0YjcxNjZmMTFmYWI1MGRiZTA2MGMwMWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xWSKg0vn6VhBlxkYD1AT9Odm2FAr7OiSIe9gPUeiz7w)
> 
> ![2024-08-24 14_15_08-EmulationStation](https://private-user-images.githubusercontent.com/105559045/361139906-100e7197-deef-4332-a1ed-b44af6986b9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTcwMjcsIm5iZiI6MTcyNTg5NjcyNywicGF0aCI6Ii8xMDU1NTkwNDUvMzYxMTM5OTA2LTEwMGU3MTk3LWRlZWYtNDMzMi1hMWVkLWI0NGFmNjk4NmI5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxNTQ1MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNzVlYTExY2U1MWZlYzA2OTkzMGZlMzZmNmQ2NGYyM2RiNjgzMjZlNTllOWRlNTQ2YTkwZjhkYmI4MzcxOTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jwrsqCtlBG7wxLvROGwfBS3MFSjJXpXTtOigNCmUNC4)
> 
> Je vais bosser un peu sur la vidéo ;) (pour info tu utilises quelle vue système ?)

Bonjour, Serait il possible de de pouvoir changer la couleur du système(menu emulstation, fond des icones de la vue grid). Je suis pas très fan du gris. doesn't fit the thème.

J'aime cette idée 
![image](https://github.com/user-attachments/assets/87187c90-9697-4133-8ec1-7da3d88ee4c1)
