### ISSUE TITLE
Theme for J2ME (Java)

### ISSUE THREAD

**Issue by erfan2255** [Snapouille/es-theme-Animatics-DX#14]
Hi there thanks for your beautiful theme. I use to play java games using j2me core, I will appreciate if you add j2me theme too, thanks

**Comment by Snapouille** [comment]
Hi, thanks for your feedback.
What games do you play with j2me ?
do you know which directory to use for that core?

**Comment by erfan2255** [comment]
Well j2me title mostly known as plants vs zombie, gangstar rio (or series), bounce tales and assassin creeds games. directory is `j2me`

**Comment by Snapouille** [comment]
I see. Can you tell me how you set up this system, and how you run the games?

**Comment by Snapouille** [comment]
I put an assassin creeds background and avatar for the java j2me. Have fun.

**Comment by erfan2255** [comment]
sorry I wasn't there for while, I used Freej2me on rg35xx plus (h700 cpu) on Knulli forks of batocera. I added patch manually using this:
https://github.com/erfan2255/FreeJ2ME-Knulli
