### ISSUE TITLE
crash retobat

### ISSUE THREAD

**Issue by benjdidj** [Snapouille/es-theme-Animatics-DX#15]
Ia orana.
retrobat plante quand je suis sur votre theme, 
quand je quitte un jeu/emulateur lors du retour sur emulstation.
Je n'ai pas ce probleme sur carbon master un autre theme retrobat.
Que puis je faire ?

Merci

**Comment by Snapouille** [comment]
Ia orana,
Hum bizarre, c'est la première fois qu'on me remonte ce genre de dysfonctionnement.
Tu es sur quelle version de Retrobat ? tu as fait des modifs custom dans Retrobat ?

Quoi qu'il en soit une grosse mise à jour du thème arrive pour ce week-end, faudra voir si tu as toujours ces problèmes de crash.

**Comment by benjdidj** [comment]
Je  suis sur la 6.3.1. modifs custom, je sais pas... J'ai sûrement touche des règles ,mais j'avais reset histoire d'être sûr . Même problème.
J'ai le même problème sur plusieurs Autres comme rvgm bt. Le gard m'as dis que vous travaillez ensemble. Comme il ne met plus a j son thème... Je me suis dis que CT ça.
 Mais il doit y en avoir d'autres qui me font la même. Je ne sais plus lesquels
Ckau-Book marche nickel, carbon master aussi. 

'''''J'ai vu sur un forum une histoire de localisation?''''''''' Je crois que d'autres personnes avait des pb similaires sur ckau.
J'espérais que la nouvelle mise a jour de retobat fixerait le pb. 

Yay une mise a jour !! On verra. Dans tous les cas. Good job. Thanks you.

**Comment by Snapouille** [comment]
C'est vraiment bizarre. Tu es sur le discord de Retrobat ? 
Si oui tu peux leur poser la question directement pour voir si d'autres personnes ont le même problème.
Oui il y a eu une mise à jour de Retrobat aussi.

**Comment by getupor** [comment]
Hello @benjdidj 
As-tu essayé de supprimer totalement le theme de Snapouille, puis de le réinstaller ?

**Comment by Snapouille** [comment]
Parfait, merci du retour
