### ISSUE TITLE
Video Snaps Aspect Ratio

### ISSUE THREAD

**Issue by mrfomt** [Snapouille/es-theme-Animatics-DX#17]
For example, Vertical Arcade games. Video snaps are being stretched to 4:3. Is there a way to show theme in their correct aspect?
Also for Game & Watch snaps are all in different aspect ratios, some of them looks weird.

Wish that, if it is possible, that all video snaps will show in their true aspect ratio, like the snapshot images do.

**Comment by Snapouille** [comment]
Hi, 
Yes I know there's a ratio problem with arcade games and game&watch, I need to find a solution. I haven't found the right one yet.
What view are you using?

**Comment by mrfomt** [comment]
Ok hope you find a solution for it.
I am using Legandary right now. Sometimes Gamecarousel.

**Comment by Snapouille** [comment]
I've finally found a solution for Legendary and Gamecarouse view.
The theme is up to date if you want to test.

![2024-11-16 11_20_36-EmulationStation](https://github.com/user-attachments/assets/cb1566df-0b67-40a7-8dfc-b80e9ab27
![2024-11-16 11_46_06-EmulationStation](https://github.com/user-attachments/assets/741a0b65-92f7-43a8-82df-84b35356e180)
5a4)

**Comment by mrfomt** [comment]
Thank you! Will test it oit. Can I just update via Batocera Theme Downloader (PC)?

**Comment by mrfomt** [comment]
It is the same as before.

![image](https://github.com/user-attachments/assets/4580ba7f-be97-4afc-8f3f-1a95e31f350f)
![image](https://github.com/user-attachments/assets/6ebd97c9-1708-4452-8e0b-7443a1ec4065)
![image](https://github.com/user-attachments/assets/2d316a6a-ba6a-48df-8aa0-da33473be18c)
![image](https://github.com/user-attachments/assets/74b94d53-011a-413a-beea-7a689ecd3ab6)

**Comment by Snapouille** [comment]
no for the g&w it's normal I haven't done it yet. 
But wait, I think you're in the arcade collection, I forgot the collections ... Can you try with fbneo or mame system ?

**Comment by Snapouille** [comment]
yes, that was it, you can run an update again

**Comment by mrfomt** [comment]
Thank you, yes I was in Arcade system. Now it is working great!
If it is not to much problem for you, than maybe you can do the same for Toaplan, Cave, CPS1-3.
Thanks again!

**Comment by Snapouille** [comment]
Finally, I've corrected all the arcade systems and collections as well as the game & watch. Thanks for the feedback, you can try it out.

![2024-11-16 17_59_16-EmulationStation](https://github.com/user-attachments/assets/8ce0993f-4de4-4d8b-8028-e90ec1d397a6)

**Comment by Snapouille** [comment]
You're welcome. Enjoy!

**Comment by mrfomt** [comment]
One thing, I have put my Game & Watch roms is gameandwatch rom folder. Is that correct?
Here I get the logo "LCD Games", and the aspect ratio is not correct.

![image](https://github.com/user-attachments/assets/1fa54a75-b9d2-466c-8f16-ad1092b664fc)

**Comment by Snapouille** [comment]
hum, you're right. I do the gameandwatch system but I forgot to do the lcdgames system, it's fix now.

![2024-11-17 09_02_31-EmulationStation](https://github.com/user-attachments/assets/7b57672d-6b77-4c34-96f6-1f0bb8d9d426)

**Comment by mrfomt** [comment]
Thanks. Where do I put the roms if I want to use the Game & Watch theme instead of LCD Games?

**Comment by mrfomt** [comment]
Get it now, was a setting in Batocera.
