### ISSUE TITLE
HELP: Question about undocumented variables inside theme.xml

### ISSUE THREAD

**Issue by worstcase-scenario** [Snapouille/es-theme-Animatics-DX#2]
Hello, great theme! I'm trying to create my own theme based on artbook and ckaubook and was studying your theme.xml when I saw that you are using a variable ( <scrollbarcolor> ), which is not mentioned in the official documentation at all. 

So now I wonder if there are more such "unknown / undocumented" variables... and perhaps if you have more knowledge and insight into this. 

I am especially am looking for any kind of variable I can use to change the font size inside a <textlist>-gamelist, when a game-title is active and selected.

Is this somehow possible? It would be great to get some advice! Thanks!

**Comment by Snapouille** [comment]
Hello,
Thank you for your word.
I don't know a variable to change the font size inside a -gamelist when is selected. The best thing you can do is ask the question on the batocera discord, # theme development. There are some talented developers there who will be able to answer your questions.

You can also follow the GIT of "batocera-emulationstation" to find out what's new :
https://github.com/batocera-linux/batocera-emulationstation/commits/master

Good luck with your theme ;)

**Comment by worstcase-scenario** [comment]
Thank you for your quick answer and your advice! I am going to try my luck on the discord server.... keep up your excellent work!
