### ISSUE TITLE
new additions

### ISSUE THREAD

**Issue by skysix2** [Snapouille/es-theme-Animatics-DX#3]
Hi!

could you add themes for: virtua fighter, soulcalibur, tekken and samurai shodown?

obviously with the calm you need and when you have time!

Thanks again for this amazing theme!!

**Comment by Snapouille** [comment]
Hi
OK, it's on my todo list for the next update 😉
Thanks for your words.

**Comment by Snapouille** [comment]
Update to v1.62

**Comment by skysix2** [comment]
super thanks!!
