### ISSUE TITLE
Problem with Powkiddy x55 Jelos 20240206

### ISSUE THREAD

**Issue by GelitoSP** [Snapouille/es-theme-Animatics-DX#4]
Hi.

First of all, congratulations to the creator since it is one of the best themes I have seen. And that's why I open this query since I would love to be able to enjoy it. But when I try to enter one of the systems to see the list of games, the system crashes and has to restart. So it is not functional in my case. Any help on this would be appreciated. If you need more information I will be happy to help with this incident.

Thanks in advance and congratulations for the great work.

**Comment by Snapouille** [comment]
Hi
Thanks for your feedback.
My theme is only compatible with Batocera and Retrobat (no Jelos). Batocera does not support Powkiddy x55 for now.
You can check the Handheld Consoles supported there :
https://batocera.org/download

I think you could ask for the powkiddy x55 to be integrated directly on the Batocera discord :
https://discord.gg/nyPjPUV9
