### ISSUE TITLE
issue with last version 1.63

### ISSUE THREAD

**Issue by skysix2** [Snapouille/es-theme-Animatics-DX#5]
HI !
after updating to version 1.63, the themes of the custom collections disappeared (for example mario, tekken etc...)
and only the MAME subcollections are visible (for example capcom, konami etc...)
on batocera v38

and I no longer understand where the theme saves its settings, I did some tests by renaming the files in system/config/emulationstation/themesettings(I don't remember the exact directory)/theme.cfg but it still keeps the settings!?!?

help !

**Comment by Snapouille** [comment]
Yes, you're right. But what happened?
On Batocera v39 and Retrobat v6, Emulation Station has evolved by offering new features. The management of collections has also changed, so I made the change but forgot that there are still people in v38.


So I'm going to back off for now and propose a theme for the versions before Batocera 39 and Retrobat v6.

**Comment by Snapouille** [comment]
I've done the backtracking, you can try updating to see if everything's OK.

**Comment by skysix2** [comment]
but v39 is not official yet !
ok i try ! thanks !!

**Comment by Snapouille** [comment]
Yes I know, but Retrobat v6 is official, so I got a bit carried away ^^

**Comment by skysix2** [comment]
ok it work !!
but where stored the configs of theme ??

thankyou !!

**Comment by Snapouille** [comment]
For retrobat it's stored here :
\Retrobat\emulationstation\.emulationstation\themesettings

It should be almost the same for batocera I think
