### ISSUE TITLE
Region setting not working

### ISSUE THREAD

**Issue by SuperMagicom** [Snapouille/es-theme-Animatics-DX#6]
The setting to select a region for logos & consoles is not working because it references by capital letters (EU,US,JP) and the folders are named in lower case letters. Re-naming the folders with the images to "US" and "JP" fixes the issue.

**Comment by Snapouille** [comment]
Thanks for your feedback. Batocera has a case sensitive that retrobat does not have.
It's corrected now, thanks again.
