### ISSUE TITLE
Gamelist detailed view problems/ stucking 

### ISSUE THREAD

**Issue by Kyo-Tachibana** [Snapouille/es-theme-Animatics-DX#7]
When I change the gamelist view to detailed and try to acess roms the screen stuck for a period and return to main screen, but when I delete gamelist file in the respective roms system folder, I can acess menu system roms, but without any info or video or image. The others options to view are working fine, but only detailed is stucking. I only use the game new order view, but I found it interesting to pass along the information. If ou need I can send a video. 
![stuck](https://github.com/Snapouille/es-theme-Animatics-DX/assets/160366830/d7c73ee1-83b6-49d6-98e8-8de3f0912671)

**Comment by Snapouille** [comment]
I don't think you have the latest theme update, are you in v1.66 ?
If not, which Retobat or Batocera system are you on, and which version?

![2024-03-13 09_55_25-Window](https://github.com/Snapouille/es-theme-Animatics-DX/assets/105559045/23c679e0-e056-45fc-9415-6f5f2fa3dc8f)

**Comment by Snapouille** [comment]
@Kyo-Tachibana have you solved your problem?

**Comment by Kyo-Tachibana** [comment]
Sorry for the late reply, I don't notified. I not solved and aswering your question, I use Jelos, but before the last update I was used the theme normally in all gamelist mode. My aspect ratio is 16:9
