### ISSUE TITLE
Query - Editing System Description

### ISSUE THREAD

**Issue by Wilmatron** [Snapouille/es-theme-Animatics-DX#8]
Hi Snapouille,

Absolutely love your theme for ES in Batocera Linux. Hoping you can point me in the right direction. I'm looking for a way to manipulate the system description text. Which file is this being pulled from? I've looked in **/userdata/themes** folder but cannot find where the text is to replace it.

I also stumbled across **/usr/share/emulationstation** and the **es_systems.cfg** but again cannot see any reference to the system description text.

To clarify; this is the text underneath the main system logo image in your theme; for example; Archimedes would be "Acorn Archimedes is the first consumer computer based on a RISC processor... etc..."

Any help would be greatly appreciated.

Cheers,
Wilma

**Comment by Snapouille** [comment]
Hi Wilma,
You can find all the files here :
![IMG_20240326_075104](https://github.com/Snapouille/es-theme-Animatics-DX/assets/105559045/299a8c92-4133-4c25-8155-8c2f1e500f7a)
Which language do you want to change to?

**Comment by Wilmatron** [comment]
Hi Snapouille,

Thanks for the quick response and pointing me to the right path - I don't know how I missed that one!
Consider the case closed.

Cheers,
Wilma

**Comment by Snapouille** [comment]
Ok, I close it.
If you ever make better translations for the systems I might be interested in integrating them directly into the theme. 

Cheers,
Snap
